[versions]
android-gradle-plugin = "8.2.0-alpha11"
detekt = "1.23.0"
kotlin = "1.8.22"
ksp = "1.8.22-1.0.11"

androidx-core = "1.10.1"
androidx-lifecycle = "2.6.1"
androidx-navigation = "2.6.0"
androidx-window = "1.1.0"

activity-compose = "1.7.2"
compose-animation = "1.5.0-beta02"
compose-compiler = "1.4.8"
compose-foundation = "1.5.0-beta02"
compose-icons = "1.5.0-beta02"
compose-material3 = "1.2.0-alpha02"
compose-runtime = "1.5.0-alpha03"
compose-ui = "1.5.0-beta02"
accompanist = "0.31.4-beta"

room = "2.6.0-alpha01"

ktor = "2.3.1"

kotlinx-coroutines = "1.7.2"
kotlinx-datetime = "0.4.0"
kotlinx-serialization-formats = "1.5.1"

koin = "3.4.2"
koin-compose = "3.4.5"

vico = "1.6.6"

junit = "4.13.2"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"

[libraries]
androidx-core = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }
androidx-lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidx-navigation" }
androidx-window = { group = "androidx.window", name = "window", version.ref = "androidx-window" }
androidx-window-testing = { group = "androidx.window", name = "window-testing", version.ref = "androidx-window" }

activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }

compose-animation = { group = "androidx.compose.animation", name = "animation", version.ref = "compose-animation" }
compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "compose-foundation" }
compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose-ui" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "compose-ui" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose-ui" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose-ui" }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "compose-ui" }
compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "compose-ui" }
compose-icons = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "compose-icons" }
compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "compose-material3" }
compose-material3-windowsizeclass = { group = "androidx.compose.material3", name = "material3-window-size-class", version.ref = "compose-material3" }
accompanist-drawablepainter = { group = "com.google.accompanist", name = "accompanist-drawablepainter", version.ref = "accompanist" }

room-runtime = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }
ktor-contentnegotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }

kotlinx-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization-formats" }

koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koin-android-compose = { group = "io.insert-koin", name = "koin-androidx-compose", version.ref = "koin-compose" }

vico = { group = "com.patrykandpatrick.vico", name = "compose-m3", version.ref = "vico" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

[bundles]
compose = [
    "activity-compose",
    "viewmodel-compose",
    "compose-animation",
    "compose-foundation",
    "compose-ui",
    "compose-ui-graphics",
    "compose-ui-tooling-preview",
    "compose-icons",
    "compose-material3",
    "compose-material3-windowsizeclass"
]
compose-tooling = [
    "compose-ui-test-manifest",
    "compose-ui-tooling"
]
