name: Code scanning

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '33 19 * * *'

jobs:
  static-analysis:
    permissions:
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v3.9.0
        with:
          java-version: 17
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run Detekt & Lint
        continue-on-error: true
        run: ./gradlew detekt lint --continue
      - name: Upload SARIF binary
        uses: actions/upload-artifact@v3
        with:
          name: sarif-reports
          path: '**/*.sarif'

  upload-results:
    needs: static-analysis
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - core/api
          - core/capacity
          - core/compose-logviewer
          - core/compose-menuprovider
          - core/compose-urllauncher
          - features/apps
          - features/auth
          - features/credentials
          - features/dashboard
          - features/dataprotection
          - features/datasets
          - features/network
          - features/reporting
          - features/shares
          - features/storage
          - features/systemsettings
          - features/virtualization
          - app
    steps:
      - name: Download scan results
        uses: actions/download-artifact@v3
        with:
          name: sarif-reports
      - name: Display structure of downloaded files
        run: ls -R
      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ matrix.path }}/
          category: ${{ matrix.path }}
